version: '3'
services:
 mssql-server:
  image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
  container_name: mssql-server
  environment:
   ACCEPT_EULA: "Y"
   SA_PASSWORD: "Password.1234"
  ports:
   - "1433:1433"
 ocelot:
  image: thinkco/ocelot
  container_name: timemanager.gateway
  ports:
   - "1080:80"
  environment:
   ACCEPT_EULA: "Y"
  volumes:
   - ./ocelotgateway:/data
  depends_on:
   - timemanager.api
   - timemanager.idp
   - seq
 seq:
  image: datalust/seq:latest
  container_name: timemanager.logs.seq
  ports:
   - "5341:80"
  environment:
   ACCEPT_EULA: "Y"
  restart: unless-stopped
  volumes:
   - ./seq-data:/data
  depends_on:
   - timemanager.api
   - timemanager.idp
 timemanager.api:
  build: ../TimeManager.API/
  container_name: timemanager.api
  environment:
   DatabaseServer: "mssql-server"
   DatabasePort: "1433"
   DatabaseUser: "sa"
   DatabasePassword: "Password.1234"
   DatabaseName: "TimeManager_API"
  depends_on:
   - mssql-server
  ports:
   - "8090:80"
 timemanager.idp:
  build: ../TimeManager.IdP/
  container_name: timemanager.idp
  environment:
   DatabaseServer: "mssql-server"
   DatabasePort: "1433"
   DatabaseUser: "sa"
   DatabasePassword: "Password.1234"
   DatabaseName: "TimeManager_IdP"
  depends_on:
   - timemanager.api
  ports:
   - "8080:80"