version: '3'
services:
 rabbitmq:
  build: ./rabbitmq/
  container_name: rabbitmq
  ports:
   - "5672:5672"
   - "15672:15672"
 mssql-server:
  image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
  container_name: mssql-server
  environment:
   ACCEPT_EULA: "Y"
   SA_PASSWORD: "Password.1234"
  ports:
   - "1433:1433" 
 timemanager.gateway:
  build: ../TimeManager.Gateway/
  container_name: timemanager.gateway
  ports:
   - "8070:80"
   - "8081:443"
  environment:
    ASPNETCORE_URLS: "https://+;http://+"
    ASPNETCORE_HTTPS: "8081"
    ASPNETCORE_ENVIRONMENT: Development
  volumes:
   - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
   - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https
  depends_on:
   - mssql-server
   - rabbitmq
 timemanager.data:
  build: ../TimeManager.DATA/
  container_name: timemanager.data
  environment:
   DatabaseServer: "mssql-server"
   DatabasePort: "1433"
   DatabaseUser: "sa"
   DatabasePassword: "Password.1234"
   DatabaseName: "TimeManager_DATA"
  depends_on:
   - timemanager.gateway
   - rabbitmq
  ports:
   - "8090:80"
 timemanager.idp:
  build: ../TimeManager.IdP/
  container_name: timemanager.idp
  environment:
   DatabaseServer: "mssql-server"
   DatabasePort: "1433"
   DatabaseUser: "sa"
   DatabasePassword: "Password.1234"
   DatabaseName: "TimeManager_IdP"
  depends_on:
   - timemanager.gateway
   - rabbitmq
  ports:
   - "8080:80"
 timemanager.processingengine:
  build: ../TimeManager.ProcessingEngine
  container_name: timemanager.processingengine
  ports:
   - "8060:80"
   - "8075:444"
  environment:
   DatabaseServer: "mssql-server"
   DatabasePort: "1433"
   DatabaseUser: "sa"
   DatabasePassword: "Password.1234"
   DatabaseName: "TimeManager_ProcessingEngine"
   ASPNETCORE_URLS: "https://+;http://+"
   ASPNETCORE_HTTPS: "8075"
   ASPNETCORE_ENVIRONMENT: Development
  restart: unless-stopped
  volumes:
   - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
   - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https
  depends_on:
   - timemanager.idp
   - timemanager.data
 seq:
  image: datalust/seq:latest
  container_name: timemanager.logs.seq
  ports:
   - "5341:80"
  environment:
   ACCEPT_EULA: "Y"
  restart: unless-stopped
  volumes:
   - ./seq-data:/data
  depends_on:
   - timemanager.data
   - timemanager.idp